=== ZavenArra/lattice/lattice/lattice/data.dtd
<?xml version="1.0" encoding="utf-8"?>

<!--
	LatticeCMS Data Configuration File DTD
	Revision: 0.1
	Date: 2010/09/18	
-->

<!ELEMENT data (nodes,relationships) >

<!ELEMENT nodes (item*) >

<!ELEMENT item (item|field|list|object)* >
<!ATTLIST item
	objectTypeName		CDATA #REQUIRED
>

<!ELEMENT field (#PCDATA|field)* >  
<!ATTLIST field
	name CDATA #REQUIRED
>

<!ELEMENT list  (item*) >
<!ATTLIST list
	family CDATA #REQUIRED
>

<!ELEMENT object (field*) >
<!ATTLIST object
	name CDATA #REQUIRED
>

<!ELEMENT relationships (lattice*) >

<!ELEMENT lattice (relationship*)>
<!ATTLIST lattice
  name CDATA #REQUIRED
>

<!ELEMENT relationship EMPTY >
<!ATTLIST relationship
  parent CDATA #REQUIRED
  child CDATA #REQUIRED
>

=== ZavenArra/lattice/latticecms/config/data.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE data SYSTEM "data.dtd">
<data>
	<item objectTypeName="basicCategory">
		<field name="title">Category 1</field>
		<item objectTypeName="basicCategory">
			<field name="title">Category 2</field>
			<item objectTypeName="basicCategory">
				<field name="title">Category 3 A</field>
			</item>
			<item objectTypeName="basicCategory">
				<field name="title">Category 3 B</field>
				<item objectTypeName="basicCategory">
					<field name="title">Category 4 A</field>
				</item>
				<item objectTypeName="basicCategory">
					<field name="title">Category 4 B</field>
				</item>
				<item objectTypeName="basicCategory">
					<field name="title">Category 4 C</field>
				</item>
			</item>
			<item objectTypeName="basicCategory">
				<field name="title">Category 3 C</field>
			</item>
		</item>
	</item>

	<item objectTypeName="singleIPE">
		<field name="title">Single IPE</field>
      <item objectTypeName="multilineIPE">
         <field name="title">Multiline as Component</field>
      </item>
	</item>

	<item objectTypeName="multilineIPE">
		<field name="title">Multiline IPE</field>
	</item>

	<item objectTypeName="singleRadioGroup">
		<field name="title">Single Radio Group</field>
	</item>
	
	<item objectTypeName="singleCheckbox">
		<field name="title">Single checkbox</field>
	</item>

	<item objectTypeName="singleDate">
		<field name="title">Single Date</field>
	</item>

	<item objectTypeName="singleTime">
		<field name="title">Single Time</field>
	</item>

 	<item objectTypeName="singleFile">
                <field name="title">Single File</field>
                <field name="file">lattice/latticetests/testdata/ctoolsAllCases.csv</field>
        </item>

        <item objectTypeName="singleImage">
                <field name="title">Single Image</field>
                <field name="file">lattice/latticetests/testdata/29305_390907843268_707068268_4114906_7182725_n.jpg</field>
                <item objectTypeName="singleImage">
                        <field name="title">Image Build Test</field>
                        <field name="file">lattice/latticetests/testdata/29305_390907843268_707068268_4114906_7182725_n.jpg</field>
                </item>
        </item>

	<item objectTypeName="simpleListModule">
		<field name="title">Simple List Module</field>
		<list family="simplelist">
			<item objectTypeName="simpleListModuleItem">
				<field name="title">THIS IS THE TITLE</field>
			</item>
		</list>
	</item>
	
	<item objectTypeName="complexListModule">
		<field name="title">Complex List Module</field>
	</item>
	
	<item objectTypeName="imageListModule">
		<field name="title">Image List</field>
	</item>
	
	<item objectTypeName="fileListModule">
		<field name="title">File List</field>
  </item>

	<item objectTypeName="singleAssociator">
		<field name="title">Associator</field>
	</item>
	<item objectTypeName="linkTest">
		<field name="title">Link Test</field>
		<object name="theLink">
			<field name="url">lasdf</field>
			<field name="label">nas as s</field>
		</object>

	</item>

	<item objectTypeName="tagsObjectType">
		<field name="title">Tags</field>
	</item>
</data>
