=== ZavenArra/lattice/latticecms/config/objects.dtd
<?xml version="1.0" encoding="utf-8"?>

<!--
	LatticeCMS Backend Configuration File DTD
	Revision: 0.1
	Date: 2010/08/26	
-->

<!ENTITY % uiattrs
	"name				CDATA	#REQUIRED
	 label				CDATA	#IMPLIED
	 className			CDATA	#IMPLIED"
>

<!ELEMENT configuration (objectTypes) >

<!ELEMENT objectTypes (objectType*) >

<!ELEMENT objectType ( elements?,addableObject*,components* ) >
<!ATTLIST objectType
	name				CDATA #REQUIRED
	nodeType			CDATA "object"
	contentType			CDATA "document"
	allowDelete 		(true|false) "true"
	allowTogglePublish	(true|false) "true"
	allowChildSort		(true|false) "true"
	sortDirection		(ASC|DESC)	"ASC"
	allowTitleEdit  CDATA "true"
>

<!ELEMENT elements (text|list|image|file|radioGroup|multiSelect|date|time|dateRange|checkbox|time|associator|link|extendedImage|extendedFile|tags)* >

<!ELEMENT components (component*) >

<!ELEMENT addableObject EMPTY >
<!ATTLIST addableObject
	objectTypeName		CDATA #REQUIRED
	addText				CDATA #IMPLIED
>

<!ELEMENT component ANY>
<!ATTLIST component
	objectTypeName	CDATA #REQUIRED
	label			CDATA #REQUIRED
>

<!ELEMENT list (addableObject*) >
<!ATTLIST list
	name				CDATA #REQUIRED
	label				CDATA #REQUIRED
	display				(inline|component)	"inline"
	allowChildSort   	(true|false)		"true"
	sortDirection		(ASC|DESC)			"ASC"
	allowTogglePublish	(true|false)		"true"	
	contentType  		CDATA "document"
>
<!-- last two attributes currently not supported -->


<!ELEMENT associator (filter*)>
<!ATTLIST associator  
	name         CDATA #REQUIRED
	label         CDATA #IMPLIED
	parent        CDATA  #IMPLIED
	objectTypeName  CDATA  #IMPLIED 
>   

<!ELEMENT filter EMPTY >
<!ATTLIST filter
	from           CDATA #IMPLIED
	objectTypeName   CDATA #IMPLIED
	tagged         CDATA #IMPLIED
>

<!ELEMENT text EMPTY >
<!ATTLIST text
	%uiattrs;
	tag					CDATA "p"
	isMultiline	(true|false) "false"
>

<!ELEMENT image (resize|ext)* >
<!ATTLIST image
	%uiattrs;
	maxLength			CDATA #IMPLIED
>

<!ELEMENT file (ext)* >
<!ATTLIST file
	%uiattrs;
	maxLength			CDATA #IMPLIED
>

<!ELEMENT radioGroup (radio*) >
<!ATTLIST radioGroup
	%uiattrs;
	groupLabel			CDATA #REQUIRED
>

<!ELEMENT radio EMPTY >
<!ATTLIST radio
	label				CDATA #REQUIRED
	value				CDATA #REQUIRED
>

<!ELEMENT multiSelect EMPTY >
<!ATTLIST multiSelect
	%uiattrs;
>


<!ELEMENT date EMPTY>
<!ATTLIST date
	%uiattrs;
>

<!ELEMENT time EMPTY>
<!ATTLIST time
	%uiattrs;
>


<!ELEMENT checkbox EMPTY>
<!ATTLIST checkbox
	%uiattrs;
>

<!ELEMENT link EMPTY>
<!ATTLIST link
	%uiattrs;
>

<!ELEMENT extendedImage EMPTY>
<!ATTLIST extendedImage 
	%uiattrs;
>

<!ELEMENT extendedFile EMPTY>
<!ATTLIST extendedFile 
	%uiattrs;
>

<!ELEMENT tags EMPTY >
<!ATTLIST tags 
	name CDATA "tags"
	label				CDATA	#IMPLIED
	className			CDATA	#IMPLIED
>

<!ELEMENT resize EMPTY >
<!ATTLIST resize
	name				CDATA #REQUIRED
	width				CDATA #REQUIRED
	height				CDATA #REQUIRED
	forceDimension		(width|height) #IMPLIED
	crop				(true|false) "false"
>

<!ELEMENT ext (#PCDATA) >

<!ELEMENT data (item*) >

<!ELEMENT item ANY >
<!ATTLIST item
	objectTypeName		CDATA #REQUIRED
>

<!ELEMENT content ANY >

<!ELEMENT title (CDATA) >

=== ZavenArra/lattice/lattice/objects.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE configuration SYSTEM "objects.dtd">

<configuration>

	<objectTypes>
		<objectType name="article" contentType="document" allowDelete="true" >
			<elements>
				<text name="multilineIPE" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE2" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE3" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE4" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE5" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE6" label="MultiLine IPE" isMultiline="true"/>
			</elements>
		</objectType>


		<objectType name="category" contentType="category" allowChildSort="false" allowDelete="false" allowTogglePublish="false">
			<addableObject objectTypeName="article" addText="Add an Article" />
		</objectType>
		
	</objectTypes>

</configuration>

=== ZavenArra/lattice/latticecms/config/objects.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE configuration SYSTEM "objects.dtd">

<configuration>

	<objectTypes>

		<objectType name="tagsObjectType" >
      <elements>
				<tags label="Tags" name="tags" />
      </elements>
		</objectType>
		
<!-- HOME -->
		<objectType name="basicCategory" contentType="category" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<addableObject objectTypeName="article" addText="Add an Article" />
			<addableObject objectTypeName="multilineIPE" addText="Add an Article" />
			<addableObject objectTypeName="singleIPE" addText="Add an Article" />
			<addableObject objectTypeName="singleDate" addText="Add an Article" />
			<addableObject objectTypeName="anotherCategory" addText="Add a Category" />
		</objectType>

		<objectType name="anotherCategory" contentType="category" allowChildSort="false" allowDelete="false" allowTogglePublish="false">
			<addableObject objectTypeName="article" addText="Add an Article" />
		</objectType>
		
		<objectType name="article" contentType="document" allowDelete="true" >
			<elements>
				<text name="multilineIPE" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE2" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE3" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE4" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE5" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE6" label="MultiLine IPE" isMultiline="true"/>
			</elements>
		</objectType>

		<objectType name="singleIPE" contentType="document" allowChildSort="true" allowDelete="true" allowTogglePublish="false">

			<elements>
				<pulldown name="state"  label="State"  >
					<option value="AL" label="Alabama" />
					<option value="AK" label="Alaska" />
				</pulldown>
				<text name="singleIPE" label="Single Single Single" isMultiline="false" />
				<text name="singleIPE2" label="Single Single Single" isMultiline="false" />
				<text name="ssdfasdfingleIPE2" label="Single Single Single" isMultiline="false" />
				<text name="ssdfasdfasdfasdfingleIPE2" label="Single Single Single" isMultiline="false" />
				<text name="maritnagus" label="NEW!" isMultiline="false" />
				<text name="lagunea" label="Test Entry" isMultiline="true" />
				<text name="lagunea1" label="Test Entry" isMultiline="true" />
				<text name="lagunea2" label="Test Entry" isMultiline="false" />
				<text name="lagunea3" label="Test Entry" isMultiline="true" />
				<text name="lagunea4" label="Test Entry" isMultiline="false" />
				<text name="lagunea5" label="Test Entry" isMultiline="false" />
				<text name="lagunea6" label="Test Entry" isMultiline="false" />
				<text name="lagunea7" label="Test Entry" isMultiline="false" />
				<text name="lagunea8" label="Test Entry" isMultiline="true" />
			</elements>
			
			<components>
				<component objectTypeName="singleDate" label="SingleDate as Component" />
				<component objectTypeName="singleFile" label="Single File as Component"/>
				<component objectTypeName="singleFile" label="Single markksl  as Component"/>
            <component objectTypeName="multilineIPE" label="Multiline as Component"/>

			</components>
		
		</objectType>

		<objectType name="multilineIPE" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="true">
			<elements>
				<text name="multilineIPE" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE2" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE3" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE4" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE5" label="MultiLine IPE" isMultiline="true"/>
				<text name="multilineIPE6" label="MultiLine IPE" isMultiline="true"/>
			</elements>
		</objectType>
		
		<objectType name="singleRadioGroup" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<elements>
        			<radioGroup name="singleRadioGroup" groupLabel="Single Radio Group">
          				<radio label="One" value="1"/>
          				<radio label="Two" value="2"/>
          				<radio label="Three" value="3"/>
        			</radioGroup>
			</elements>
		</objectType>

		<objectType name="singleCheckbox" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<elements>
				<checkbox name="singleCheckbox" label="Single Checkbox"/>
			</elements>
		</objectType>

		<objectType name="singleDate" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<elements>
				<date name="singleDate" label="Single Date"/>
			</elements>
		</objectType>

		<objectType name="singleTime" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<elements>
				<time name="singleTime" label="Single Time"/>
			</elements>
		</objectType>

		<objectType name="singleFile" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<elements>
				<file name="file" label="Single File"/>
			</elements>
		</objectType>

		<objectType name="singleImage" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<elements>
				<image name="file" label="Single Image">
					<resize name="test" width="96" height="58" forceDimension="height" /> 
					<resize name="uithumb" width="6" height="8" forceDimension="height" /> 
					<ext>jpg</ext>
    				 <ext>tiff</ext>
      				 <ext>tif</ext>
				</image>
				<text name="singleIPE2" label="Single Single Single" isMultiline="false" />
				<text name="singleIPE3" label="Single Single Single" isMultiline="false" />
				<text name="singleIPE4" label="Single Single Single" isMultiline="false" />
				<text name="singleIPE5" label="Single Single Single" isMultiline="false" />
			</elements>
		</objectType>

		<objectType name="simpleListModule" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<elements>
				<list name="simplelist" label="Simple List Module" display="inline">
					<addableObject objectTypeName="simpleListModuleItem"  addText="Add a field"/>
				</list>
			</elements>
		</objectType>

		<objectType name="simpleListModuleItem" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<elements>
				<text name="description" label="Description"/>
				<text name="detail1" label="Detail 1"/>
				<text name="detail2" label="Detail 2"/>
			</elements>
		</objectType>
			
		<objectType name="imageListModule" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<elements>
				<list name="imageList" label="Image List" display="inline">
					<addableObject objectTypeName="imageListItem" addText="Add an image"/>
				</list>
			</elements>	
		</objectType>
		
		<objectType name="imageListItem" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<elements>
				<text name="description" label="Description"/>		
				<image name="file">
					<ext>jpg</ext>
				</image>
			        <image name="fileTwo">
         				 <ext>jpg</ext>
        			</image>
			</elements>
		</objectType>
		
		<objectType name="fileListModule" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<elements>
				<list name="fileList" label="File List" display="inline" >
            <addableObject objectTypeName="fileListItem" addText="Add a field"/>
        </list>
      </elements>
		</objectType>

		<objectType name="fileListItem" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<elements>
	     <text name="description" label="Description"/>
	     <file name="file" label="File">
	             <ext>html</ext>
	             <ext>csv</ext>
	             <ext>txt</ext>
	             <ext>pdf</ext>
	     </file>
			</elements>
		</objectType>
	
		<objectType name="complexListModule" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<elements>
				<list name="complexList" label="Complex List" display="inline">
					<addableObject objectTypeName="complexListItem" addText="Add List"/>
				</list>
			</elements>
		</objectType>
		
		<objectType name="complexListItem" contentType="document" allowChildSort="true" allowDelete="false" allowTogglePublish="false">
			<elements>
				<text name="description" label="Description"/>
				<checkbox name="singleCheckbox" label="One"/>
				<radioGroup name="singleRadioGroup" groupLabel="Single Radio Group">
         		 		<radio label="One" value="1"/>
          				<radio label="Two" value="2"/>
          				<radio label="Three" value="3"/>
        			</radioGroup>
				<file name="file" label="File">
					<ext>html</ext>
					<ext>csv</ext>
          <ext>txt</ext>
          <ext>pdf</ext>
				</file>
			</elements>
		</objectType>			

		<objectType name="singleAssociator" >
			<elements>
				<associator name="association">
					<filter></filter>
				</associator>
			</elements>
		</objectType>
		<objectType name="linkTest" >
      <elements>
				<link name="theLink" label="A Link for All"/>
      </elements>
			<addableObject objectTypeName="linkTest" addText="Add Link Test"/>
		</objectType>




		<objectType name="wildflowerTestObject" >
      <elements>
				<image name="image" label="Image of the Wildflower"/>
      </elements>
		</objectType>

	</objectTypes>

</configuration>
